//
// Created by guobao.sun on 2021/4/29.
//

#ifndef ANDROID_CRYPTO_PADDING_H
#define ANDROID_CRYPTO_PADDING_H

#define ZERO_PADDING 0
#define PKCS1_PADDING 1
#define PKCS7_PADDING 2
#define ISO10126_PADDING 3

#endif //ANDROID_CRYPTO_PADDING_H
